Initial setup and add reading endpoint
naconnors/ambi-go pull request #2
Opened 2022-11-30 00:23 UTC by naconnors

Initial setup of db connection and add reading endpoint. A lot of this will be refactored in future changes to make it more testable and maintainable.

2022-11-30 16:13 UTC, jhodapp requested changes
Looking great for a first PR for the project Nick! Some inline thoughts and suggested changes.

2022-11-30 16:13 UTC, jhodapp commented on README.md
> +To allow Ambi-go to access your Postgresql cluster via localhost, make sure your `/etc/postgresql/14/main/pg_hba.conf` looks like the following:
If you're amenable to the idea, let's still just call it Ambi and have the -go part be an implementation detail of the repo name. That's how I approached it with Ambi-rs.

2022-11-30 16:13 UTC, jhodapp commented on main.go
> +	db, err = sql.Open("pgx", "postgres://postgres:postgres@localhost/ambi_go_dev")
Excellent, I like how you didn't overthink this first addition and just inlined the DB credentials here. Easy to build on this and formalize in the next one.

2022-11-30 16:13 UTC, jhodapp commented on main.go
> +// Use global database for now, this should be changed later
```suggestion
// FIXME Use global database for now, this should be changed later
```

I encourage adding explicit FIXME's or TODO's since most editors pick up on these and make them plainly obvious to go back and change.

2022-12-01 00:17 UTC, naconnors commented on README.md
> +To allow Ambi-go to access your Postgresql cluster via localhost, make sure your `/etc/postgresql/14/main/pg_hba.conf` looks like the following:
That is fine. I will change it.

2022-12-01 00:18 UTC, naconnors commented on main.go
> +	_ "github.com/jackc/pgx/v5/stdlib"
It just means you aren't going to use anything from the package but you need it to run the init function from the package.

2022-12-01 01:29 UTC, jhodapp commented on main.go
> +	_ "github.com/jackc/pgx/v5/stdlib"
Cool thanks for explaining!

2022-12-02 01:16 UTC, jhodapp approved these changes
LGTM

2022-12-02 01:19 UTC, merged